name: Conditional Job Execution based on Folder Changes

on:
  push:
    branches:
      - main

jobs:
  jobA:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.commits[*].added, 'src/**') || contains(github.event.commits[*].modified, 'src/**') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add steps for job A

  jobB:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.commits[*].added, 'b/') || contains(github.event.commits[*].modified, 'b/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add steps for job B

  jobC:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.commits[*].added, 'c/') || contains(github.event.commits[*].modified, 'c/')) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add steps for job C
