name: CI Workflow

on:
  push:
    branches:
      - main  # Replace with your branch name if needed
    paths:
      - .github/workflows/demo.yml
      - src/**
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Name of the job to run'
        required: true
        default: 'job1'
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'src/App.jsx'
              - 'src/main.jsx'
            frontend:
              - 'src/index.css'

  # JOB to build and test backend code
  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' && github.event.inputs.job_name == 'job1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      

  # JOB to build and test frontend code
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
